### ISSUE TITLE
tfsChatExtensions.constants.tfsServerIcon returns 404 on TFS 2015.

### ISSUE THREAD

**Issue by NikGovorov** [nuts4dotnet/TFSChatExtensions#6]
It's `/_static/tfs/12/_content/tfs-large-icons.png` on TFS 2015.

Thoughts?

**Comment by jcoutch** [comment]
When I initially added that image, I didn't think about the version number.  Even the way I have it set up for VSO, that version number probably won't exist at some point.

I'll look into adding a generic image to identify system messages, and base64 encode it so it's part of the script.

**Comment by NikGovorov** [comment]
Sounds good. Thanks.

**Comment by jcoutch** [comment]
I'm going to hard-code the image to `//www.visualstudio.com/favicon.ico`.  I could have it use /favicon.ico from the server, but if it's running in a virtual directory, the favicon of the server may not be the VSO logo.  So, this seems like the simplest option for now.
