### ISSUE TITLE
Changeset referencing always uses default collection(hard coded DefaultCollection).

### ISSUE THREAD

**Issue by NikGovorov** [nuts4dotnet/TFSChatExtensions#7]
We use named collection 'Contoso' so our changeset url looks like: `http://tfs.contoso.com/tfs/Contoso/Pacs-Genetec-SecurityCenter/_versionControl/changeset/31265`.
TFS supports multiple named collections. Room url has collectionName parameter: `http://tfs.contoso.com/tfs/_rooms#name=RoomName&collectionName=Contoso&_a=today`

Thoughts? Should we get collection name from url?

**Comment by jcoutch** [comment]
Yeah, that sounds good.  When I get a chance, I can take a look at all the places where that might need to change.  Might just be the changeset url's and possibly the user's image (although the root-level API should grab the image too.)
